### ISSUE TITLE
Vergen git commit

### ISSUE THREAD

**Issue by GaetanLepage** [cosmic-utils/tasks#20]
Now that `tasks` seems to have semantic versions, wouldn't it be worth to remove the `GIT_COMMIT_SHA` and `GIT_COMMIT_DATE` env variables approach ?

**Comment by GaetanLepage** [comment]
Ok ! Feel free to close this issue then :)

**Comment by edfloreshz** [comment]
Thanks! I'll keep it open, at some point we'll want to remove this.

**Comment by edfloreshz** [comment]
Closed by 61c98938179794c68eb5837b12e2e41090f00caf

**Comment by GaetanLepage** [comment]
Thanks ! Btw, do you plan to tag a new release ? I have seen that many additions have been made since [0.1.0](https://github.com/cosmic-utils/tasks/releases/tag/0.1.0).

**Comment by edfloreshz** [comment]
Yes, I'll make a new release today.

**Comment by edfloreshz** [comment]
https://github.com/cosmic-utils/tasks/releases/tag/0.1.1

**Comment by GaetanLepage** [comment]
Thanks a lot :)
