### ISSUE TITLE
Renaming list removes prefix icon from list

### ISSUE THREAD

**Issue by iamkartiknayak** [cosmic-utils/tasks#25]
In the attachment provided below TaskList1, 2, 3 have been renamed and it is observed consistently that renaming a list removes the prefix icon associated with it which affects the visual consistency. 
![Screenshot from 2024-07-13 19-50-53](https://github.com/user-attachments/assets/63ad984e-00c1-4acc-9d58-85e08175b326)
.

**Comment by edfloreshz** [comment]
Thanks for reporting this! I'll take a look
