### ISSUE TITLE
Feautre request: zoom to make text larger or smaller.

### ISSUE THREAD

**Issue by MatchaJello** [cosmic-utils/tasks#26]
I would like to see a feature added to have the ability to zoom in and out with ctrl + & ctrl -.

**Comment by edfloreshz** [comment]
I think this might be handled by accessibility at some point by COSMIC, is that correct? @mmstick

**Comment by mmstick** [comment]
There will be toolkit options in libcosmic at some point

**Comment by edfloreshz** [comment]
Then I don't see any reason to work on this per app, instead let the DE handle it.
