### ISSUE TITLE
[bug][flatpak] Issue with theme not changing to light mode

### ISSUE THREAD

**Issue by DelicateIntegral** [cosmic-utils/tasks#31]
**ISSUE**:
- Whenever I click on the menu buttons, if I don't click on any option and try to move the cursor away, it automatically starts to drag the entire window of the application.
- The font size/zoom level is very high by default and there is no option to change it.
- The application always remain in dark mode no matter what i select in settings.

> [!note]
> **System INFO**:
>  OS: Linux
>  DE: KDE
>  App Type: Flatpak
>  Build Commit (from About section in application): [3786d06](https://github.com/cosmic-utils/tasks/commits/3786d06bfcff83d1b749c08cee985ce236dc4ad8)

**Comment by DelicateIntegral** [comment]
Well I was trying another app and it has also same issue. I checked and found that it was also related to cosmic.
Just today I used wayland (I wanted to try waydroid). And the issue of window dragging and app being zoomed are resolved.
The issue of theme still being dark even when light is selected still persists.

**Comment by DelicateIntegral** [comment]
It would be good to add a warning to make users aware to use wayland instead of x11.

Example:

> [!caution]
> X11 has issues with cosmic apps.
> Use wayland.

**Comment by edfloreshz** [comment]
I tried replicating this but the Flatpak version does follow the theme mode.

https://github.com/user-attachments/assets/89ff2645-41d2-48ab-821a-866493a80573

**Comment by edfloreshz** [comment]
Closing for now, we can reopen in the future if it becomes reproducible.
